# Do not adopt new versions of dependency libraries within the first 24 hours of their release (to reduce the risk of supply chain attacks).
minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@ota-meshi/*"
  - esrap
  - svelte
  - typescript-eslint-parser-for-extra-files
