name: Bug report
description: Create a report to help us improve.

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: sanity-checks
    attributes:
      label: Before You File a Bug Report Please Confirm You Have Done The Following...
      description: If any of these required steps are not taken, we may not be able to review your issue. Help us to help you!
      options:
        - label: I'm using [eslint-plugin-svelte](https://github.com/sveltejs/eslint-plugin-svelte). (`*.svelte` file linting does not work with the parser alone. You should also use eslint-plugin-svelte with it.)
        - label: I'm sure the problem is a parser problem. (If you are not sure, search for the issue in [eslint-plugin-svelte](https://github.com/sveltejs/eslint-plugin-svelte) repo and open the issue in [eslint-plugin-svelte](https://github.com/sveltejs/eslint-plugin-svelte) repo if there is no solution.
          required: true
        - label: I have tried restarting my IDE and the issue persists.
          required: true
        - label: I have updated to the latest version of the packages.
          required: true
  - type: input
    id: eslint-version
    attributes:
      label: What version of ESLint are you using?
      placeholder: 0.0.0
    validations:
      required: true
  - type: textarea
    id: eslint-plugin-svelte-version
    attributes:
      label: What version of `eslint-plugin-svelte` and ` svelte-eslint-parser` are you using?
      value: |
        - svelte-eslint-parser@0.0.0
        - eslint-plugin-svelte@0.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you do?
      description: |
        Please include a *minimal* reproduction case.
      value: |
        <details>
        <summary>Configuration</summary>

        ```
        <!-- Paste your configuration here -->
        ```
        </details>

        ```svelte
        <!-- Paste your code here -->
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
      description: |
        You can use Markdown in this field.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What actually happened?
      description: |
        Please copy-paste the actual ESLint output. You can use Markdown in this field.
    validations:
      required: true
  - type: textarea
    id: bug-reproduction
    attributes:
      label: Link to **GitHub Repo** with Minimal Reproducible Example
      description: |
        Create a minimal reproduction of the problem. **A minimal reproduction is required** so that others can help debug your issue. If a report is vague (e.g. just a generic error message) and has no reproduction, it may be closed.  
        [Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required)  

        Be sure to share the repo on GitHub. GitHub's repo is ready to debug using Codespace.  
        Please DON'T USE non-GitHub repos such as GitLab as repro.  
        It takes me a long time to prepare my local PC for debugging.  
        Please DON'T USE stackblitz as a repro.  
        We can't debug eslint with stackblitz.
      placeholder: |
        https://github.com/[your]/[repo]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional comments
