# Do not adopt new versions of dependency libraries within the first 24 hours of their release (to reduce the risk of supply chain attacks).
minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - svelte
  - "@ota-meshi/*"
  - typescript-eslint-parser-for-extra-files
  # Renovate security update: webpack@5.104.1
  - webpack@5.104.1
  # Renovate security update: @sveltejs/kit@2.52.2
  - "@sveltejs/kit@2.52.2"
