name: 👔 Format

on:
  workflow_dispatch: null

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      - name: Install Packages
        run: pnpm install --frozen-lockfile
      - name: Format
        run: pnpm run eslint-fix
      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "no formatting changed"
            exit 0
          fi
          pnpm update prettier
          git add .
          git commit -m "chore: format"
          git push
          echo "pushed formatting changes https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"
